baseurl = "/"
languageCode = "en-us"
title = "Nix Theme"
theme = "hugo-theme-nix"

[params]
  GithubID = "your_github"
  TwitterID = "your_twitter"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "Toorusr"
  HeaderUsername = "root"
  HeaderHostname = "toorusr.md"
  Email = "your_email"
  About = "info_about_you"
  ProfilePicture = "https://github.com/toorusrsite/ToorWeb2/blob/master/media/ueberblcik.png?raw=true"
  GoogleAnalytics = "your_google_analytics_id"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "Impressum"
    weight = 0
    url = "/Impressum"
